name: Update APL Bear

on:
  push:
    paths:
      - 'static/sims/bear/guardian_df.txt'

defaults:
  run:
    working-directory: static/sims

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: actions/checkout@v3
      - name: checkout simc
        uses: actions/checkout@v3
        with:
          repository: simulationcraft/simc
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: './simc'
          ref: dragonflight
      - name: generate APL
        run: python generate_apl.py --spec=bear --df "./simc"
      - name: commit APL
        run: |
          git log -1 --pretty=format:"%B%ndreamgrove/Dreamgrove@%h" > commit_msg
          echo >> commit_msg
          echo >> commit_msg
          echo "Co-authored-by: Dreamgrove <dreamgrove@github.com>" >> commit_msg
          git config --global user.name $(git log -1 --format=%aN)
          git config --global user.email $(git log -1 --format=%aE)
          cd simc
          if [ -z "$(git status --porcelain)" ]; then
            echo "no changes to apl"
          else
            git add .
            git commit -F ../commit_msg
            git push
          fi
